# Generated by Django 5.1.3 on 2024-11-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_reserva_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='preco_diaria',
        ),
    ]
