# Generated by Django 5.1.3 on 2024-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_quarto_preco_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
